# Generated by Django 4.1.7 on 2023-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_alter_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
