# Generated by Django 4.1.7 on 2023-02-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_is_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
