# Generated by Django 4.1.7 on 2023-05-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
